DefaultContentLanguage = "en"
baseURL = "https://boring-thompson-f3381b.netlify.app/"
enableEmoji = true
theme = "introduction"
[languages.en]
contentDir = "content/en"
languageCode = "en-us"
languageName = "English"
title = "AriefB Intro"
weight = 0
[languages.en.params]
description = "Introduction AriefB"
footerText = "Natura Est Deus In Rebus"
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
dateFormat = "Jan 2, 2006"
email = "ariefbuddies@qmail.id"
fadeIn = true
fadeInIndex = true
favicon = "/img/fav.ico"
showRSSButton = false
themeStyle = "light"
[params.home]
introHeight = "fullheight"
localTime = false
numberOfProjectsToShow = 3
showAllPosts = true
showLatest = false
timeFormat = "h:mm A"
timeZone = "Asia/Jakarta"
[params.projects]
useTwoColumns = false
[params.share]
facebook = false
googlePlus = false
pinterest = false
twitter = true
[[params.social]]
icon = "twitter"
icon_pack = "fab"
url = "https://twitter.com/"
[[params.social]]
html_attributes = "rel=\"me\""
icon = "paper-plane"
icon_pack = "fas"
url = "mailto:ariefbuddies@qmail.id"
[taxonomies]
tag = "tags"
